antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'pulsar'
site:
  title: Spring Pulsar
  url: https://docs.spring.io/spring-pulsar/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
    - url: https://github.com/spring-projects/spring-pulsar
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: [ main, '({1..9}).+({0..9}).x' ]
      tags: [ 'v({1..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(v1.0.0-M({0..2}))']
      start_path: spring-pulsar-docs/src/main/antora
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-pulsar
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.3.6/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
